version: "3.8"

services:
  web:
    build: .
    container_name: django_web
    command: sh -c "python manage.py migrate && gunicorn sneeds_speedfeed.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432
volumes:
  postgres_data:
