# Generated by Django 5.2 on 2025-05-13 05:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('photo', models.CharField(max_length=512, null=True)),
                ('description', models.TextField(null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('photo', models.CharField(max_length=512)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ein', models.PositiveIntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('photo', models.CharField(max_length=512, null=True)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_billing_address', to='speedfeed_app.address')),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_delivery_address', to='speedfeed_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.IntegerField(choices=[(1, 'Original'), (2, 'Substitution')])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=3)),
                ('currency', models.CharField(max_length=5)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing_address', to='speedfeed_app.address')),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.contractor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.customer')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_address', to='speedfeed_app.address')),
                ('items', models.ManyToManyField(through='speedfeed_app.ItemInOrder', to='speedfeed_app.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='iteminorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.order'),
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event_type', models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Abandoned'), (4, 'Picked Up'), (5, 'Delivered'), (6, 'Disputed'), (7, 'Resolved'), (8, 'Archived')])),
                ('photo', models.CharField(max_length=512, null=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.contractor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('photo', models.CharField(max_length=512, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('currency', models.CharField(max_length=5)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.address')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedfeed_app.restaurant'),
        ),
    ]
